utils::globalVariables(c(":=", "CV",
                         "ONTOLOGY", "Description", "pvalue", "GO_pathway",
                         "org.Hs.eg.db", "org.Mm.eg.db",
                         "pvalue", "FoldEnrichment", "Description",
                         "count", "S", "Y", "STY", "pct_S", "pct_T", "pct_Y",
                           "amino_acid_type", "amino_acid_facet", ".data",
                         "KSData", "Kinase.Gene", "Substrate.Gene", "Substrate.Mod",
                         "Kinases", "Substrates", "stratum", "m", "z.score", "p.value",
                           "point_color", "CELL_META",
                         "grpstreat", "grpscontrol",
                         "ID",
                         "Probability", "Sample", "phosphosites", "Group", "Number_of_phosphosites",
                         "Protein_group", "Number_of_proteins",
                         "uniprot_accessions"))
